name: Eslint

on:
  push:
    paths:
      - 'frontend/**/*.{js,jsx,ts,tsx}'
  pull_request:
    paths:
      - 'frontend/**/*.{js,jsx,ts,tsx}'

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      working-directory: frontend
      run: npm install

    - name: Run ESLint
      working-directory: frontend
      run: npm run lint
