name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    # # Use the "production" environment so we can access environment secrets defined there
    # environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Make environment variables
        run: |
          echo "FIREBASE_CONFIG=${{ secrets.FIREBASE_CONFIG }}" >> .env.local
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env.local
          echo "SECRET=${{ secrets.NEXT_PUBLIC_SECRET }}" >> .env.local
          echo "NEXTAUTH_URL=slug-events-next-app--slug-events-448506.us-central1.hosted.app" >> .env.local
          echo "NEXT_PUBLIC_LOGIN_URL=https://slug-events-398513784123.us-west1.run.app/login" >> .env.local
          echo "NEXT_PUBLIC_BACKEND_URL=https://slug-events-398513784123.us-west1.run.app" >> .env.local
          echo "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}" >> .env.local
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env.local
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env.local

      - name: Install dependencies and build
        run: |
          cd frontend
          npm ci
          npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SLUG_EVENTS_448506 }}
          projectId: slug-events-448506
          entryPoint: frontend
